import { useMemo } from 'react';

export const useGenreData = () => {
  return useMemo(() => [
    {
      id: 'pulse',
      name: 'PULSE',
      label: 'Hip-Hop/Rap',
      day: 'Monday',
      time: '6 AM',
      color: 'bg-red-600',
      subscribers: 15420,
      engagement: 42.3,
      growth: 18.7,
      revenue: 28450,
      emoji: '🎤',
      description: 'Underground hip-hop trends, emerging rappers, and street culture intelligence',
      demoAvailable: false
    },
    {
      id: 'storyteller',
      name: 'STORYTELLER',
      label: 'Singer-Songwriter',
      day: 'Tuesday',
      time: '6 PM',
      color: 'bg-green-600',
      subscribers: 12300,
      engagement: 51.2,
      growth: 15.8,
      revenue: 24600,
      emoji: '🎸',
      description: 'Intimate singer-songwriter discoveries, confessional folk movement, and authentic storytelling',
      demoAvailable: true,
      featured: true
    },
    {
      id: 'voltage',
      name: 'VOLTAGE',
      label: 'Electronic/EDM',
      day: 'Tuesday',
      time: '6 AM',
      color: 'bg-blue-600',
      subscribers: 18750,
      engagement: 45.1,
      growth: 24.6,
      revenue: 35800,
      emoji: '⚡',
      description: 'Electronic music evolution, festival intelligence, and producer spotlights',
      demoAvailable: false
    },
    {
      id: 'resonance',
      name: 'RESONANCE',
      label: 'Pop/Mainstream',
      day: 'Thursday',
      time: '6 AM',
      color: 'bg-pink-600',
      subscribers: 28900,
      engagement: 35.8,
      growth: 8.9,
      revenue: 42500,
      emoji: '✨',
      description: 'Pop culture analysis, mainstream trends, and commercial music intelligence',
      demoAvailable: false
    },
    {
      id: 'amplify',
      name: 'AMPLIFY',
      label: 'Rock/Alternative',
      day: 'Wednesday',
      time: '6 PM',
      color: 'bg-slate-700',
      subscribers: 14250,
      engagement: 38.9,
      growth: 12.3,
      revenue: 26800,
      emoji: '🎸',
      description: 'Rock revival movements, garage bands, and alternative scene intelligence',
      demoAvailable: false
    },
    {
      id: 'rhythm',
      name: 'RHYTHM',
      label: 'R&B/Soul',
      day: 'Friday',
      time: '6 AM',
      color: 'bg-amber-700',
      subscribers: 11650,
      engagement: 44.7,
      growth: 16.2,
      revenue: 23400,
      emoji: '🎵',
      description: 'Modern R&B evolution, soul revivals, and smooth vocal trends',
      demoAvailable: false
    },
    {
      id: 'underground',
      name: 'UNDERGROUND',
      label: 'Indie/Experimental',
      day: 'Saturday',
      time: '10 AM',
      color: 'bg-teal-600',
      subscribers: 9820,
      engagement: 56.3,
      growth: 21.5,
      revenue: 19600,
      emoji: '🌙',
      description: 'Experimental sounds, bedroom producers, and avant-garde movements',
      demoAvailable: false
    },
    {
      id: 'crossroads',
      name: 'CROSSROADS',
      label: 'Country/Americana',
      day: 'Sunday',
      time: '8 AM',
      color: 'bg-yellow-700',
      subscribers: 13450,
      engagement: 40.1,
      growth: 14.8,
      revenue: 25200,
      emoji: '🤠',
      description: 'Modern country trends, Americana roots, and Nashville intelligence',
      demoAvailable: false
    },
    {
      id: 'pencraft',
      name: 'PENCRAFT',
      label: 'Songwriting Craft',
      day: 'Wednesday',
      time: '6 AM',
      color: 'bg-emerald-700',
      subscribers: 8940,
      engagement: 62.4,
      growth: 19.3,
      revenue: 21500,
      emoji: '✍️',
      description: 'Songwriting techniques, lyrical analysis, and creative process deep-dives',
      demoAvailable: false
    },
    {
      id: 'hitmaker',
      name: 'HITMAKER',
      label: 'Commercial Songwriting',
      day: 'Friday',
      time: '6 PM',
      color: 'bg-orange-600',
      subscribers: 10250,
      engagement: 48.6,
      growth: 17.9,
      revenue: 24800,
      emoji: '🎯',
      description: 'Hit songwriting formulas, sync licensing opportunities, and commercial trends',
      demoAvailable: false
    },
    {
      id: 'executive',
      name: 'EXECUTIVE',
      label: 'Music Business Strategy',
      day: 'Thursday',
      time: '6 PM',
      color: 'bg-gray-800',
      subscribers: 12890,
      engagement: 53.2,
      growth: 22.1,
      revenue: 38900,
      emoji: '💼',
      description: 'Industry deals, label insights, investment trends, and executive intelligence',
      demoAvailable: false
    },
    {
      id: 'revenue',
      name: 'REVENUE',
      label: 'Artist Business',
      day: 'Monday',
      time: '6 PM',
      color: 'bg-green-800',
      subscribers: 11340,
      engagement: 59.8,
      growth: 25.4,
      revenue: 34200,
      emoji: '💰',
      description: 'Monetization strategies, streaming economics, touring business, and artist income',
      demoAvailable: false
    }
  ], []);
};
