import { useMemo } from 'react';

export const useGenreData = () => {
  return useMemo(() => [
    {
      id: 'pulse',
      name: 'PULSE',
      label: 'Hip-Hop/Rap',
      day: 'Monday',
      time: '6 AM',
      color: 'bg-red-600',
      subscribers: 15420,
      engagement: 42.3,
      growth: 18.7,
      revenue: 28450,
      emoji: '🎤',
      description: 'Underground hip-hop trends, emerging rappers, and street culture intelligence',
      demoAvailable: false
    },
    {
      id: 'storyteller',
      name: 'STORYTELLER',
      label: 'Singer-Songwriter',
      day: 'Tuesday',
      time: '6 PM',
      color: 'bg-green-600',
      subscribers: 12300,
      engagement: 51.2,
      growth: 15.8,
      revenue: 24600,
      emoji: '🎸',
      description: 'Intimate singer-songwriter discoveries, confessional folk movement, and authentic storytelling',
      demoAvailable: true,
      featured: true
    },
    {
      id: 'voltage',
      name: 'VOLTAGE',
      label: 'Electronic/EDM',
      day: 'Tuesday',
      time: '6 AM',
      color: 'bg-blue-600',
      subscribers: 18750,
      engagement: 45.1,
      growth: 24.6,
      revenue: 35800,
      emoji: '⚡',
      description: 'Electronic music evolution, festival intelligence, and producer spotlights',
      demoAvailable: false
    },
    {
      id: 'resonance',
      name: 'RESONANCE',
      label: 'Pop/Mainstream',
      day: 'Thursday',
      time: '6 AM',
      color: 'bg-pink-600',
      subscribers: 28900,
      engagement: 35.8,
      growth: 8.9,
      revenue: 42500,
      emoji: '✨',
      description: 'Pop culture analysis, mainstream trends, and commercial music intelligence',
      demoAvailable: false
    },
    {
      id: 'amplify',
      name: 'AMPLIFY',
      label: 'Rock/Alternative',
      day: 'Wednesday',
      time: '6 PM',
      color: 'bg-slate-700',
      subscribers: 14250,
      engagement: 38.9,
      growth: 12.3,
      revenue: 26800,
      emoji: '🎸',
      description: 'Rock revival movements, garage bands, and alternative scene intelligence',
      demoAvailable: false
    },
    {
      id: 'rhythm',
      name: 'RHYTHM',
      label: 'R&B/Soul',
      day: 'Friday',
      time: '6 AM',
      color: 'bg-amber-700',
      subscribers: 11650,
      engagement: 44.7,
      growth: 16.2,
      revenue: 23400,
      emoji: '🎵',
      description: 'Modern R&B evolution, soul revivals, and smooth vocal trends',
      demoAvailable: false
    },
    {
      id: 'underground',
      name: 'UNDERGROUND',
      label: 'Indie/Experimental',
      day: 'Saturday',
      time: '10 AM',
      color: 'bg-teal-600',
      subscribers: 9820,
      engagement: 56.3,
      growth: 21.5,
      revenue: 19600,
      emoji: '🌙',
      description: 'Experimental sounds, bedroom producers, and avant-garde movements',
      demoAvailable: false
    },
    {
      id: 'crossroads',
      name: 'CROSSROADS',
      label: 'Country',
      day: 'Sunday',
      time: '8 AM',
      color: 'bg-yellow-700',
      subscribers: 13450,
      engagement: 40.1,
      growth: 14.8,
      revenue: 25200,
      emoji: '🤠',
      description: 'Modern country trends, Nashville intelligence, and traditional country roots',
      demoAvailable: false
    },
    {
      id: 'roots',
      name: 'ROOTS',
      label: 'Americana',
      day: 'Sunday',
      time: '2 PM',
      color: 'bg-orange-800',
      subscribers: 9850,
      engagement: 48.2,
      growth: 16.5,
      revenue: 19700,
      emoji: '🎻',
      description: 'Americana roots, folk traditions, bluegrass revival, and authentic storytelling',
      demoAvailable: false
    },
    {
      id: 'thunder',
      name: 'THUNDER',
      label: 'Metal',
      day: 'Friday',
      time: '8 PM',
      color: 'bg-zinc-900',
      subscribers: 16320,
      engagement: 52.8,
      growth: 19.4,
      revenue: 31200,
      emoji: '🤘',
      description: 'Heavy metal evolution, underground scenes, thrash to doom, and extreme music intelligence',
      demoAvailable: false
    },
    {
      id: 'hearth',
      name: 'HEARTH',
      label: 'Folk',
      day: 'Thursday',
      time: '7 PM',
      color: 'bg-lime-700',
      subscribers: 8640,
      engagement: 61.5,
      growth: 17.2,
      revenue: 17800,
      emoji: '🪕',
      description: 'Traditional folk music, acoustic storytelling, world folk traditions, and organic sounds',
      demoAvailable: false
    },
    {
      id: 'tribute',
      name: 'TRIBUTE',
      label: 'Cover/Tribute',
      day: 'Saturday',
      time: '4 PM',
      color: 'bg-rose-700',
      subscribers: 11450,
      engagement: 46.3,
      growth: 13.7,
      revenue: 22900,
      emoji: '🎭',
      description: 'Cover artists, tribute bands, reimagined classics, and the art of musical interpretation',
      demoAvailable: false
    },
    {
      id: 'pencraft',
      name: 'PENCRAFT',
      label: 'Songwriting Craft',
      day: 'Wednesday',
      time: '6 AM',
      color: 'bg-emerald-700',
      subscribers: 8940,
      engagement: 62.4,
      growth: 19.3,
      revenue: 21500,
      emoji: '✍️',
      description: 'Songwriting techniques, lyrical analysis, and creative process deep-dives',
      demoAvailable: false
    },
    {
      id: 'hitmaker',
      name: 'HITMAKER',
      label: 'Commercial Songwriting',
      day: 'Friday',
      time: '6 PM',
      color: 'bg-orange-600',
      subscribers: 10250,
      engagement: 48.6,
      growth: 17.9,
      revenue: 24800,
      emoji: '🎯',
      description: 'Hit songwriting formulas, sync licensing opportunities, and commercial trends',
      demoAvailable: false
    },
    {
      id: 'lyricist',
      name: 'LYRICIST',
      label: 'Lyric Writing',
      day: 'Tuesday',
      time: '9 AM',
      color: 'bg-purple-700',
      subscribers: 7820,
      engagement: 55.3,
      growth: 20.1,
      revenue: 18400,
      emoji: '📝',
      description: 'Lyrical techniques, metaphor mastery, wordplay, and poetic songwriting',
      demoAvailable: false
    },
    {
      id: 'narrative',
      name: 'NARRATIVE',
      label: 'Storytelling',
      day: 'Saturday',
      time: '9 AM',
      color: 'bg-indigo-700',
      subscribers: 8450,
      engagement: 60.7,
      growth: 18.9,
      revenue: 20100,
      emoji: '📖',
      description: 'Song storytelling techniques, narrative structures, and character development in music',
      demoAvailable: false
    },
    {
      id: 'executive',
      name: 'EXECUTIVE',
      label: 'Music Business Strategy',
      day: 'Thursday',
      time: '6 PM',
      color: 'bg-gray-800',
      subscribers: 12890,
      engagement: 53.2,
      growth: 22.1,
      revenue: 38900,
      emoji: '💼',
      description: 'Industry deals, label insights, investment trends, and executive intelligence',
      demoAvailable: false
    },
    {
      id: 'revenue',
      name: 'REVENUE',
      label: 'Artist Business',
      day: 'Monday',
      time: '6 PM',
      color: 'bg-green-800',
      subscribers: 11340,
      engagement: 59.8,
      growth: 25.4,
      revenue: 34200,
      emoji: '💰',
      description: 'Monetization strategies, streaming economics, touring business, and artist income',
      demoAvailable: false
    },
    {
      id: 'connect',
      name: 'CONNECT',
      label: 'Engagement',
      day: 'Wednesday',
      time: '3 PM',
      color: 'bg-cyan-700',
      subscribers: 10580,
      engagement: 57.4,
      growth: 23.2,
      revenue: 26300,
      emoji: '🤝',
      description: 'Fan engagement strategies, social media growth, community building, and audience connection',
      demoAvailable: false
    },
    {
      id: 'ledger',
      name: 'LEDGER',
      label: 'Finances',
      day: 'Friday',
      time: '9 AM',
      color: 'bg-emerald-800',
      subscribers: 9240,
      engagement: 64.1,
      growth: 21.8,
      revenue: 29800,
      emoji: '📊',
      description: 'Music industry finances, royalty accounting, tax strategies, and financial planning for artists',
      demoAvailable: false
    }
  ], []);
};
